services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - "./grafana.ini:/etc/grafana/grafana.ini"
