services:
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    volumes:
      - "./grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - grafana

# RESTRICTION: must declare a network
networks:
  grafana:
